#! /bin/sh
### BEGIN INIT INFO
# Provides:          door-switch
# Required-Start:    $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Switch to open door.
### END INIT INFO

nohup /usr/bin/door_switch.py > /dev/null 1>&2 &

exit 0
