#! /bin/sh
### BEGIN INIT INFO
# Provides:          start-door-monitor
# Required-Start:    $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Monitors ADA fruit door feed and opens if it is set to open.
### END INIT INFO

nohup /usr/bin/start_door_monitor.py > /dev/null 2>&1 &

exit 0
